### ISSUE TITLE
v0.7 todos and changes

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/messaging-apis#314]
- [x] use class methods instead of class properties #310
- [x] separate-test-files
- [x] use official prettier to style markdown files and put config into package.json #293
- [x] fix doc links 
- [x] update dependencies
- [x] update docs after release

#### messenger

- [x] move message creation api into singleton `Messenger` #255
- [x] rename getDailyUniqueActiveThreadCounts to getActiveThreads #307
- [x] add 2 new metrix to messenger insights, remove deprecated #304
- [x] Messenger Insights API: resolve obj instead of [obj] #302
- [x] fix getReportedConversationsByReportType and improve docs #297
- [x] update tags for Messenger Platform 2.3 #295 
- [x] remove deprecated MessengerClient methods #315
- [x] batch request factories #317

#### line

- [x] allow pass object as image, audio, video, sticker args #309
- [x] Alias LineClient.xxxButtonsTemplate to LineClient.xxxButtonTemplate #320

#### telegram

- [x] Throw error when ok is false in Telegram #268
- [x] telegram api return result instead of { ok: true, result } #313
